---
- name: Check if atom is installed
  command: dpkg-query -W {{ atom_packagename }}
  register: atom_check_deb
  failed_when: atom_check_deb.rc > 1
  changed_when: atom_check_deb.rc == 1

- debug: var=atom_check_deb

- name: Download atom
  get_url: 
    url="{{ atom_package_url }}"
    dest="{{ ansible_user_dir }}/.cache/"
  when: atom_check_deb.rc == 1

- name: Install atom
  apt: deb="{{ ansible_user_dir }}/.cache/{{ atom_packagename }}-amd64.deb"
  sudo: true
  when: atom_check_deb.rc == 1
